version: "3"

services:
  frontend:
    networks:
      - gq_network
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - frontend:/app/build

  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile.https
    ports:
      - 80:8080
      - 443:443
    volumes:
      - static:/vol/static
      - frontend:/var/www/frontend

networks:
  gq_network:
    driver: bridge

volumes:
  static:
  frontend: